name: Automerge

on:
  push:
    branches: 
      - master

env:
  MY_REPO: https://Piotr-Glab495:${{ secrets.UGV_PAT }}@github.com/Piotr-Glab495/UWB-Geolocalisation-Visualizer.git
  MY_BRANCH: development
  MASTER_BRANCH: master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge with master
      run: |
        git config url.https://${{ secrets.UGV_PAT }}@github.com/.insteadOf https://github.com/
        git clone ${{ env.MY_REPO }} -b ${{ env.MY_BRANCH }} tmp
        cd tmp
        git config user.name "Automerge Bot"
        git config user.email "automergeBot@example.com"
        git config pull.rebase false
        git pull ${{ env.MY_REPO }} ${{env.MASTER_BRANCH}}
        git push
